- app/workers/long_form_contact_worker.rb
- app/workers/problem_report_worker.rb
- app/workers/zendesk_ticket_worker.rb
This change moves all Zendesk-related logic for anonymous feedback to
the ZendeskTicketWorker, rather than the logic being sprinkled across
several classes.
> Better encapsulation of Zendesk

- app/models/content_item.rb
- app/models/organisation.rb
- app/models/support/requests/anonymous/problem_report.rb
- app/workers/content_item_enrichment_worker.rb
- app/workers/problem_report_worker.rb
- config/application.rb
- config/initializers/content_api.rb
- db/migrate/20141230121133_add_content_items_and_organisations.rb
- db/schema.rb
- lib/content_api/base_info_lookup.rb
- lib/content_api/depts_and_policy_content_lookup.rb
- lib/content_api/enhanced_content_api.rb
- lib/content_api/gds_owned_content_lookup.rb
- lib/content_api/mainstream_info_lookup.rb
- lib/content_api/orgs_content_lookup.rb
- lib/content_api/worldwide_orgs_content_lookup.rb
- lib/support_api.rb
- spec/models/content_api/enhanced_content_api_spec.rb
- spec/requests/problem_reports_spec.rb
In order to present relevant anonymous feedback to users in departments and ALBs, we need to know which organisation is interested in a particular piece of feedback. This can be done by looking up at the orgs that relate to the piece of content that originated the problem report.
The org information is retrieved from the Content API and persisted; this saves having to fetch a list of all content relating to a particular org, and trying to get the feedback for each one of those paths.
More details about the implementation in the commit messages.
> Identify content items, organisations for each problem report

- db/migrate/20150115215320_add_index_on_anonymous_contacts_path.rb
- db/schema.rb
This speeds up the FeedEx 'find feedback by path' queries.
> Add index on path in the 'anonymous_contacts' table

- app/models/organisation.rb
- lib/content_api/base_info_lookup.rb
- spec/models/content_api/enhanced_content_api_spec.rb
- spec/models/workers/content_item_enrichment_worker_spec.rb
- spec/requests/problem_reports_spec.rb
This is a follow-PR to #26. It contains hardening of the feature and fixes issues found during testing on Preview:
- incorrect parameters being passed to the Content API
- handle the case when the Content API returns 404 for a slug
- bolster test coverage around problem report enrichment
> Content identification fixes

- Gemfile
- Gemfile.lock
This fixes the deprecation warning that started appearing after the upgrade to rails 4.2.0.
> Bump rails-api to v0.4.0

- config/initializers/content_api.rb
- lib/content_api/enhanced_content_api.rb
- lib/content_api/orgs_content_lookup.rb
- spec/models/content_api/enhanced_content_api_spec.rb
Before this change, the code made the false assumption that organisation
info can be found in the Content API. After this change, org info is fetched
from the Content Store.
> Fix the org lookup for organisation pages

- lib/content_api/gds_owned_content_lookup.rb
- spec/models/content_api/enhanced_content_api_spec.rb
A couple of days ago, the report-a-problem form was added to the homepage
(https://www.gov.uk). This commit enables the organisation-identification
code to handle those problem reports without throwing an exception.
Trigger for this: https://errbit.production.alphagov.co.uk/apps/53be43010da11516ee0007a7/problems/54ca667e0da1156623002322
> Handle problem reports raised on the homepage

- db/migrate/20150313183713_remove_low_quality_single_word_feedback.rb
- db/schema.rb
This feedback has been analysed and shown to be almost never actionable.
> Remove low-quality single-word feedback from the Contacts DB

- db/schema.rb
The ActiveRecord schema dumper has changed between Rails 4.1.X and 4.2.X. This PR brings the `schema.rb` in line with the new behaviour, so that any schema changes in subsequent migrations are minimised. See the individual commits for more details.
/cc @mikejustdoit
> Upgrade schema to be compatible with the Rails 4.2.X schema dumper

- lib/content_api/default_org_content_lookup.rb
- lib/content_api/enhanced_content_api.rb
- spec/models/content_api/enhanced_content_api_spec.rb
- spec/models/workers/content_item_enrichment_worker_spec.rb
The support-api was raising regular exceptions in
Errbit:`NoMethodError: undefined method 'content_item_path' for nil:NilClass`
Wrote a test to recreate the bug, fixed it by adding a default org lookup
which will assign to GDS any content items that could not be associated with
another organisation.
cc @benilovj
[Taiga story](https://tree.taiga.io/project/core-improvement-theme/us/6)
> Bugfix: fixed NoMethod Error bugs

- app/models/support/requests/anonymous/anonymous_contact.rb
- spec/models/support/requests/anonymous/anonymous_contact_spec.rb
- spec/models/support/requests/anonymous/problem_report_spec.rb
Tightened path validation, as Errbit was throwing error
"No implicit conversion of nil into String" when path was "".
Path can no longer be nil
[Taiga story](https://tree.taiga.io/project/core-improvement-theme/us/14)
cc @benilovj
> Bugfix: path can no longer be empty string

- db/migrate/20150430133750_replace_empty_paths.rb
- db/schema.rb
Following a bug fix, entries with nil path will now be filtered by the validation
of the AnonymousContact class. Now replacing value of historic entries that
had a path set to nil, to a path of '/'.
cc @benilovj 
[Taiga](https://tree.taiga.io/project/core-improvement-theme/us/14)
Don't merge until #37 is deployed.
> Database migration to remove nil path entries

- db/migrate/20150505100000_replace_empty_or_null_paths.rb
This is necessary prior to adding a not-null constraint on the path
column.
Migration `20150430133750_replace_empty_paths.rb` didn't go quite far
enough to catch all of these records.
The timestamp on the new migration is before `20150505162618_path_not_null.rb`
so it runs before that one.
/cc @binaryberry
> Migration to update empty paths to "/"

- app/models/support/requests/anonymous/corporate_content_problem_report_aggregated_metrics.rb
- app/models/support/requests/anonymous/problem_report.rb
- app/workers/problem_report_stats_pp_uploader_worker.rb
- config/schedule.rb
- lib/tasks/performance_platform_uploads.rake
- spec/integration/corporate_content_problem_report_stats_spec.rb
- spec/models/support/requests/anonymous/corporate_content_problem_report_aggregated_metrics_spec.rb
- spec/models/workers/problem_report_stats_pp_uploader_worker_spec.rb
The monthly upload of corporate content stats to the PP used to live
and run within the Support app, but belongs within the Support API,
closer to the data.
This upload was originally added to the Support app in https://github.com/alphagov/support/pull/156.
This data supports provides data to the feedback modules of the
performance platform GOV.UK web traffic dashboards
(https://www.gov.uk/performance/web-traffic).
> Migrate the corporate content PP upload from Support app

- app/models/support/requests/anonymous/anonymous_contact.rb
- app/models/support/requests/anonymous/problem_report.rb
- db/schema.rb
- spec/models/support/requests/anonymous/anonymous_contact_spec.rb
Some time ago, the `AnonymousContact#path` started being used instead
of `AnonymousContact#url`.
Currently:
- no endpoints accept the `url` as an attribute
- `path` has a not-null constraint 
- all the non-null paths in the database have been cleaned up
This means that we can drop all remaining uses of the `url` field and derive it from `path` completely. The next step would be dropping the column from the database, once the Support app no longer relies on
the database.
> Derive the AnonymousContact url from path

- app/workers/service_feedback_pp_uploader_worker.rb
It seems that I was too overzealous in https://github.com/alphagov/support-api/pull/49
and removed a require that's necessary for the worker to run.
This fixes an [errbit issue](https://errbit.preview.alphagov.co.uk/apps/53be40ba0da1154d55001fcb/problems/555a840d65786342cf270000).
> Reinstate necessary require statement

- app/controllers/anonymous_feedback_controller.rb
Before this fix, the page limits weren't being applied to the ActiveRecord
queries because of inappropriate use of Kaminari. This meant that
for paths with lots of feedback, everything was being loaded into
memory before being limited to just one page.
The fix means that the limits are applied directly in the DB query.
> Query the database more efficiently in AnonymousFeedbackController

- app/controllers/anonymous_feedback_controller.rb
- app/models/anonymous_contact.rb
- db/migrate/20150518151221_add_index_to_anonymous_contacts_on_created_at.rb
- db/schema.rb
- spec/controllers/anonymous_feedback_controller_spec.rb
- spec/integration/corporate_content_problem_report_stats_spec.rb
- spec/integration/deduplication_spec.rb
- spec/models/anonymous_contact_spec.rb
- spec/spec_helper.rb
Support-api can now return anonymous contacts for selected date ranges. 
The date ranges are inclusive, can be given in non-chronological order, and the app can handle none, 1 or 2 dates being defined. 
Anonymous contacts also indexed by creation date.
Also moved Timecop.return to spec_helper to ensure it was run after each test.
> Add support for date ranges

- app/controllers/anonymous_feedback/organisations_controller.rb
- app/models/content_item.rb
- config/routes.rb
- import.rb
- spec/models/content_item_spec.rb
- spec/requests/organisations_spec.rb
This is useful for being able to present FeedEx users with an overview
on which pages have had the most feedback left recently on them.
eg `/anonymous-feedback/organisations/hm-revenue-customs`:
```
{
slug: "hm-revenue-customs",
title: "HM Revenue & Customs",
anonymous_feedback_counts: [
{
path: "/government-gateway",
last_7_days: 0,
last_30_days: 0,
last_90_days: 1
},
...
}
```
This is in support of https://tree.taiga.io/project/core-improvement-theme/us/12
@mikejustdoit note that I made a small renaming in the API interface (`results => anonymous_feedback_counts`) which will affect the corresponding Support app code.
/cc @boffbowsh @binaryberry @fofr
> Endpoint for each organisation with recent feedback counts

- app/models/organisation.rb
- config/schedule.rb
- db/migrate/20150521102732_add_organisation_acronym_and_status.rb
- db/migrate/20150521140644_add_content_id_to_organisations.rb
- db/migrate/20150521144116_fill_organisation_content_ids.rb
- db/schema.rb
- lib/organisation_importer.rb
- lib/tasks/import_organisations.rake
- spec/factories/anonymous_feedback.rb
- spec/lib/organisation_importer_spec.rb
- spec/requests/organisations_spec.rb
Steals an example from the needs_api. Will require a new set of
credentials creating for whitehall API and adding to the deployment
scripts.
Also added new acronym and govuk_status fields to organisations.
/cc @benilovj @mikejustdoit
> Add rake task to import Organisations from Whitehall

- app/models/content_item.rb
- db/migrate/20150526095541_add_index_for_organisation_summary.rb
- db/schema.rb
We only count results in the last 90 days, so we should pre-filter them. Adding the index speeds this up on preview from ~7 seconds to under a second.
> Add an index to speed up organisation summary page

- Gemfile
- Gemfile.lock
- app/controllers/anonymous_feedback/export_requests_controller.rb
- app/controllers/anonymous_feedback_controller.rb
- app/controllers/application_controller.rb
- app/mailers/export_notification.rb
- app/models/anonymous_contact.rb
- app/models/feedback_export_request.rb
- app/presenters/feedback_csv_row_presenter.rb
- app/views/export_notification/notification_email.text.erb
- app/workers/generate_feedback_csv_worker.rb
- config/routes.rb
- db/migrate/20150522151256_create_feedback_export_requests.rb
- db/schema.rb
- spec/controllers/anonymous_feedback/export_requests_controller_spec.rb
- spec/factories/anonymous_feedback.rb
- spec/mailers/export_notification_spec.rb
- spec/mailers/previews/export_notification_preview.rb
- spec/models/anonymous_contact_spec.rb
- spec/models/feedback_export_request_spec.rb
- spec/models/workers/generate_feedback_csv_worker_spec.rb
- spec/presenters/feedback_csv_row_presenter_spec.rb
Takes a date range, a path prefix and an email address to notify as parameters. It then enqueues a Sidekiq job which generates the CSV and dumps it in `/data/uploads/feedback_explorer`. This is a mounted NFS path and will be available to both frontend and backend boxes. The link in the email will eventually make the support app ask nginx to send the correct CSV to the user using the `X-Accel-Redirect` header.
Work to come to support this on the front end:
/cc @benilovj @evilstreak @bradleywright
> Add Export to CSV option for Feedback reports

- app/controllers/anonymous_feedback/organisations_controller.rb
- app/controllers/organisations_controller.rb
- config/routes.rb
- spec/controllers/anonymous_feedback/organisations_controller_spec.rb
- spec/controllers/organisations_controller_spec.rb
- spec/factories/anonymous_feedback.rb
Move the Organisation index into a separate controller as it’s
unrelated to anonymous feedback
Add an Organisation show action to retrieve the title etc for a single
organisation
Add a spec for the org summary action
Backwards-compatible for the support app as the `/anonymous-feedback/organisations` endpoint still works, but should be removed.
> Refactor organisation-related endpoints

- app/controllers/anonymous_feedback/export_requests_controller.rb
- app/controllers/anonymous_feedback_controller.rb
- app/models/anonymous_contact.rb
- app/models/content_item.rb
- app/models/feedback_export_request.rb
- app/models/organisation.rb
- app/models/problem_report.rb
- db/migrate/20150604140707_serialise_export_filters.rb
- db/schema.rb
- spec/controllers/anonymous_feedback/export_requests_controller_spec.rb
- spec/controllers/anonymous_feedback_controller_spec.rb
- spec/factories/anonymous_feedback.rb
- spec/models/anonymous_contact_spec.rb
- spec/models/feedback_export_request_spec.rb
Taiga: https://tree.taiga.io/project/core-improvement-theme/us/52
Problem Reports are categorised by Organisation, so they should be filterable by Organisation too. Passing an `organisation_slug` parameter to the API will only return Problem Reports associated with that Organisation. Service Feedback and Long Form Contacts aren't currently associated with an org, so they will never be returned.
This includes some refactoring to support multiple future types of filter for CSVs, by storing the filter parameters as a serialised hash in the database.
> Allow filtering feedback by Organisation

- Gemfile
- Gemfile.lock
This picks up a fix for a bug that meant Zendesk ticket creation
failed silently if the Zendesk API suddenly started returning redirects.
> Bump gds-zendesk gem to 1.0.5

- db/migrate/20150611133227_remove_blank_dates.rb
- db/schema.rb
There was a short scan of GOV.UK in November 2012 using the [Vega](https://subgraph.com/vega/) vulnerability scanning tool.
This populated some feedback forms with various maliciously crafted strings
and submitted them. There doesn’t seem to be any side effects from
this, except that somehow created_at and updated_at dates were set to
blank for just 3 of the records.
The information provided is meaningless, so this migration simply
deletes the records.
It will find other records with blank (not NULL) dates and delete them,
but as a safeguard it’ll just refuse to do anything if it finds more
than 10 records.
This work is needed because attempting to import the data into Postgres
in this state will make it fail the NOT NULL constraints on these
columns.
> Remove feedback records with invalid dates

- lib/tasks/synchronise_mysql_to_postgresql.rake
The sync task relies on `Rails.env` being set, which is populated in the Rails boot process
/cc @benilovj
> Require Rails environment to be set up for sync task

- config/application.rb
- config/database.yml
- db/migrate/20150623151655_add_path_index_with_varchar_pattern_ops.rb
- db/schema.rb
- db/structure.sql
This index will be used in the case where a user is filtering for feedback over a large time period, probably encompassing all feedback. In this case, PostgreSQL will rightly ignore the index. The previous index on `path` was not able to be used with `LIKE` filters, so we add `varchar_pattern_ops`, same as the main composite index.
> Add index on path using PostgreSQL's varchar_pattern operator class

- db/migrate/20150915134640_deduplicate_organisations.rb
- db/structure.sql
- lib/tasks/import_organisations.rake
The cron job to import organisations now only runs on a single machine, instead of every machine concurrently. This lead to a race condition where duplicate organisations could be created. This also deduplicates the organisations in the database
> Deduplicate organisations

- app/models/content_item.rb
- app/workers/content_item_enrichment_worker.rb
- spec/models/workers/content_item_enrichment_worker_spec.rb
- spec/requests/problem_reports_spec.rb
Before this change, the owning organisation for each piece of content was only determined when the content was first seen. This meant that for content where the owning org was updated, the changes were never picked up.
https://trello.com/c/WK0EqQUl/100-content-in-feedex-incorrectly-appearing-for-dvsa-filter-medium
/cc @jamiecobbett @boffbowsh @binaryberry
> Owning organisation(s) for each problem report now updated each time one comes in

- Gemfile
- Gemfile.lock
- lib/zendesk/ticket.rb
The custom date fields on Zendesk tickets are no longer set
for other Zendesk tickets, and in this app these fields were
never populated anyway, so we can safely not send them to Zendesk.
I've tested this by:
- pushing this branch to Preview
- raising a problem report
- making sure that the ticket lands in Zendesk successfully
/cc @binaryberry @boffbowsh
> Bump gds_zendesk gem, no longer set the date fields on Zendesk tickets

- app/controllers/anonymous_feedback_controller.rb
- app/models/anonymous_contact.rb
- spec/controllers/anonymous_feedback_controller_spec.rb
For queries that will return a lot of results, fetching the initial result count is very expensive (20s for over 3 million results).
Luckily, Rails can do a `COUNT` with `LIMIT` in PostgreSQL. If you specify a limit as part of a scope then call `.count`, it will generate SQL like this:
```sql
SELECT COUNT(count_column) FROM 
(SELECT 1 AS count_column FROM "anonymous_contacts" 
WHERE path LIKE '/done/vehicle-tax%' 
LIMIT 10000) subquery_for_count;
```
This returns in around 20ms on a dev VM for a query that would return 3 million rows if unlimited. It provides 10000 responses over 200 pages for the user, with the last page rendering in about 100ms.
If the user requires all responses, they can still export them all as a CSV. Currently only 28 paths have more than 10000 responses, all of …
> Make pagination more performant

- app/models/organisation.rb
- db/migrate/20151202212408_clean_up_org_without_content_id.rb
- db/migrate/20151203001139_make_organisation_content_ids_not_null.rb
- db/structure.sql
- lib/organisation_lookups/catchall_assign_to_gds.rb
- lib/organisation_lookups/content_api_with_organisations.rb
- lib/organisation_lookups/content_store_with_organisations.rb
- lib/organisation_lookups/govuk_team_owned_pages.rb
- lib/organisation_lookups/worldwide_organisation_pages.rb
- spec/factories/anonymous_feedback.rb
- spec/models/organisation_lookup_spec.rb
- spec/models/workers/content_item_enrichment_worker_spec.rb
- spec/requests/problem_reports_spec.rb
This PR:
- makes `content_id` mandatory for all orgs
- cleans up the org without a `content_id`
- uses `content_id`s when dynamically creating orgs that aren't imported yet in the nightly import. This allows the reconciliation which happens during import to work correctly.
Open TODOs:
~~f64eff7 should probably move the code out of the migration into a more generic data hygiene class that's unit tested~~
/cc @jamiecobbett
> Use content_ids to reconcile orgs between the saved DB and the Content Store/API

- Gemfile
- Gemfile.lock
- app/workers/service_feedback_pp_uploader_worker.rb
- spec/models/workers/service_feedback_pp_uploader_worker_spec.rb
As of Dec 2015, creating service feedback datasets for each new transaction
in the Performance Platform is a manual process done by the PP team.
It's often the case that feedback starts coming into the Support API for
transactions that don't yet have a dataset for collecting this data.
Until the dataset is created, the Support API should silently consume the
failure. The data is still retained in the Support API DB, in case it needs
to be backfilled to the PP.
I've discussed this with @bmwelby.
Before merging:
> Suppress error message when pushing to Performance Platform

- config/routes.rb
- spec/requests/organisations_spec.rb
This has been replaced by the '/organisations' endpoint and the only
consumer of this endpoint (the Support app) has been moved to the new
endpoint.
(this tech task was languishing on a long-forgotten TODO list of mine for a year).
> Remove unused '/anonymous-feedback/organisations' endpoint

- lib/service_feedback_aggregator.rb
Unlike updated_at, created_at is indexed, which makes the query a lot
faster.
> Use created_at to check service feedback date

- lib/service_feedback_aggregator.rb
- spec/models/service_feedback_aggregator_spec.rb
When running the rake task for several consecutive dates, check_reason_for_not_running
mistakenly thought it had already aggregated every other date, due to a date boundary issue.
This addresses it.
Paired with @mgrassotti, cc @boffbowsh
> Fix SF aggregator bug for consecutive dates

- app/presenters/feedback_csv_row_presenter.rb
- spec/factories/anonymous_feedback.rb
- spec/models/service_feedback_aggregator_spec.rb
- spec/presenters/feedback_csv_row_presenter_spec.rb
CSV exports showed an empty cell for aggregated feedback lines, instead of the "Rating of 1: 12" type details field that is displayed in the view. This fixes it and ensures CSV exports include this details field.
This also improves two existing tests:
1. When testing different ratings, we shouldn't expect results in a specific order. This
test was failing intermittently.
2. The test for different dates only had different times, not a different day. This
fixes it.
This work was carried out pairing with @mgrassotti, and tested on integration by deploying this branch, and then exporting a CSV for a /done/ page as well as a regular page.
[Trello](https://trello.com/c/TVlBgbol/425-feedex-aggregation-not-adding-up-correctly)
> Add aggregated feedback details to CSV exports

- app/controllers/anonymous_feedback/export_requests_controller.rb
- app/controllers/anonymous_feedback/global_export_requests_controller.rb
- app/mailers/global_export_notification.rb
- app/models/global_export_csv_generator.rb
- app/models/global_export_request.rb
- app/views/global_export_notification/notification_email.text.erb
- app/workers/generate_global_export_csv_worker.rb
- config/routes.rb
- spec/controllers/anonymous_feedback/global_export_requests_controller_spec.rb
- spec/models/global_export_csv_generator_spec.rb
[Trello card](https://trello.com/c/ptXseJEJ/13-export-global-anonymous-feedback-csv)
This generates and emails (as an attachment) a CSV file containing two
fields; `date` and `report_count`, for all anonymous feedback submitted
to GOV.UK.
The aim here is to provide a mechanism to export this data so that
statistical analysis can be performed. At the moment this analysis
happens on data from zendesk; we'd like to avoid sending all types of
anonymous feedback to zendesk, so we need to have another way to provide
the data.
> Allow export of Global statistics

- app/models/content_item.rb
- spec/models/content_item_spec.rb
In the database for the `support-api`, it's possible for there to be multiple `ContentItem`'s for a given `path`. Case in point:
irb(main):005:0> ContentItem.where(path: '/calculate-your-holiday-entitlement').count
=> 255
When a problem report is raised, a representation of the content item relating to that problem report is persisted to the database.
The process of accessing this content item is pretty convoluted, and reading the code it would *appear* to be trying to update the existing content item in the database if one already exists, but it appears that this isn't happening.
Unpicking this code requires a significant refactor and some reasonable understanding of the GOV.UK content API/content stores/publishing API, which I don't have yet, but in the meantime let's fix the user …
> Group organisation report summaries by path

- app/controllers/anonymous_feedback/export_requests_controller.rb
- spec/controllers/anonymous_feedback/export_requests_controller_spec.rb
[Trello card](https://trello.com/c/lkPUHwQD/31-csv-export-on-feedback-includes-all-feedback-rather-than-just-the-dates-requested)
When performing an export request, we should use 'from' and 'to', not 'from_date' and 'to_date', as these are not present in the incoming hash.
This means that export requests have *never* respected dates.
> Correctly parse dates for export requests

- config/initializers/secret_token.rb
As this is an API only app, the key shouldn't be used, but we need to define it
anyway.
> Replace key with randomly generated version

- app/controllers/page_improvements_controller.rb
- app/models/page_improvement.rb
- config/routes.rb
- spec/models/page_improvement_spec.rb
- spec/requests/page_improvements_spec.rb
The service manual wants a way to allow users to give positive feedback, as well as negative.
This receives feedback requests from the feedback frontend on behalf of the 'Improve this page' widget and forwards the feedback to Zendesk. https://trello.com/c/HN1L3EfK/286-update-footer-feedback-component
There isn't a requirement to browse the feedback anywhere apart from on Zendesk so we avoid the "Anonymous Feedback" flow in this app.
The 'Improve this page' feature is an experiment on the Service Manual. Traffic is expected to be very low. Therefore performance hasn't been taken seriously. Notably we are communicating with Zendesk synchronously. This will make the widget less snappy but has the advantage of being able to report to the user if it was successful.
> Send page improvements to Zendesk

- app/workers/content_item_enrichment_worker.rb
- lib/content_api_lookup.rb
- lib/content_item_lookup.rb
- lib/content_store_lookup.rb
- lib/looked_up_content_item.rb
- spec/lib/content_item_lookup_spec.rb
- spec/workers/content_item_enrichment_worker_spec.rb
The content item enrichment is ending up with multiple content items with the same path in the database. This makes no sense.
I've not been able to work out why -- the code seemed pretty straightforward.
Instead, I've refactored how content item lookups happen so that they return data structures only, which are then interpreted into the database records in a single place (the enrichment worker). This means that there can't be any side effects outside this class that result in duplicates being created.
This should reduce the frequency of it happening again while I bash my head against a brick wall trying to figure out why.
> Refactor content item enrichment

- lib/organisation_importer.rb
- spec/lib/organisation_importer_spec.rb
Following the `gds-api-adapters` version bump the hash syntax for the
organisation importer is wrong. This fixes both the importer and the
test.
> Fix hash syntax for Organisation importer

- app/controllers/anonymous_feedback_controller.rb
We have some classes used by the rails app inside of lib. Controllers
explicitly require these classes but in this case the AnonymousFeedbackController
didn’t.
This was causing an error when running locally, but doesn’t surface on
deployed environments because they run in production mode which will
eager load.
In lieu of refactoring to put these classes in the app folder, this just
updates the controller to require the DateParser class.
> Fix missing date_parser require

- lib/looked_up_content_item.rb
- spec/workers/content_item_enrichment_worker_spec.rb
The [`content_api`](https://github.com/alphagov/govuk_content_api) has
been retired, and all content has been migrated to the
[`content_store`](https://github.com/alphagov/content-store).
Therefore, we can remove all references to the Content API, and rely
solely on the Content Store.
https://trello.com/c/TsUsUwD7/153-remove-documentation-on-content-api
> Remove references to the Content API

- lib/fix_misreported_done_page_service_feedback.rb
- lib/tasks/fix_misreported_service_feedback.rake
- spec/lib/fix_misreported_done_page_service_feedback_spec.rb
For a couple of weeks in March 2017 the done page template sent the
service feedback form submissions to the support-api with the wrong
path - it used the slug of the service instead of the full path to
the done page (e.g. register-to-vote instead of /done/register-to-vote).
This meant that the service feedback was stored against the incorrect
url and couldn't be found in the feedback explorer for the done page.
Here we introduce an object that given a set of dates and a slug will
re-assign any service feedback (and aggregated service feedback) for
`/slug` to `/done/slug`.  There's also a version that will extract all
done pages that have some service feedback and fix all of them.
This feels safe to do because none of the /slug pages had a form on
them for submitting service feedback …
> Provide rake task to fix misreported done page service feedback

- lib/fix_misreported_done_page_service_feedback.rb
- spec/lib/fix_misreported_done_page_service_feedback_spec.rb
For: https://trello.com/c/xZ97pseN/160-fix-data-in-feedex-for-done-pages-from-2nd-to-20th-march-2017
The system only pushes yesterday's aggregated service feedback to the
performance platform and doesn't look for changes it hasn't handled. This
means that after fixing the slugs in the aggregated feedback (see #110) we 
have to send it to the performance platform manually.  We do this inline 
rather than run them as jobs to get immediate feedback.
We don't need to remove the old data from the performance platform
as it would never have been sent.  The code that gets the aggregated
details for sending them to the perf platform will only load data for
`/done/` paths and the misreported feedback didn't have `/done/` in
the path so wouldn't have been sent.
> Push fixed misreported service feedback to performance platform

- app/presenters/feedback_csv_row_presenter.rb
- spec/models/feedback_export_request_spec.rb
- spec/presenters/feedback_csv_row_presenter_spec.rb
For: https://trello.com/c/wuROphQ5/175-add-org-column-to-feedex-reports-was-one-off-report-feedex
We add "primary organisation" and "all organisations" columns to the feedback CSV.  This is in response to a request for a one-off report that we might as well make available to all reports.
> Add org details to feedback csv

- app/models/anonymous_contact.rb
- app/validators/referrer_url_validator.rb
- spec/models/anonymous_contact_spec.rb
Only check that a URI can be parsed.
Referrer URLs can come from a variety of places eg web URLs as well as
app URLs such as “android-app://com.google.android.googlequicksearchbox”
Before this change we were rejecting otherwise valid feedback from
Android users.
https://trello.com/c/lF8Yated/66-2-http-feedback-frontend-error
https://errbit.publishing.service.gov.uk/apps/5319fd4f0da11511b00017c3/problems/597880526578634a2e330200
> Be more lenient on the referrers we accept

- app/workers/service_feedback_pp_uploader_worker.rb
- lib/fix_misreported_done_page_service_feedback.rb
- lib/performance_platform_service_feedback_metrics.rb
- spec/lib/fix_misreported_done_page_service_feedback_spec.rb
- spec/lib/performance_platform_service_feedback_metrics_spec.rb
When aggregate feedback for a time period is empty we were raising an exception, seemingly to halt the flow and prevent the empty data being sent to performance platform. There was a test that checked that the error was swallowed when it was raised but not all callers of the code
were catching the error. This was causing it to be raised within the worker and then reported multiple times to Sentry when the job was retried.
This commit removes the exception and checks the `total` value from the payload instead using that to decide whether to send to performance platform or not.
[Trello](https://trello.com/c/btVExJP7/379-identify-and-fix-high-volume-sentry-errors)
> Stop raising when no aggregate feedback

- LICENCE
- README.md
For: https://trello.com/c/O9BAVPvE/303-improve-readme-for-support-api-application
There's a styleguide for our [READMEs](https://docs.publishing.service.gov.uk/manual/readmes.html)
and the readme for this app was pretty out of date.  This is particularly annoying as the interplay
between the `support`, `support-api`, and `feedback` applications is confusing, so keeping the
readme uptodate is an opportunity to try to clarify things.
We also add a license file (MIT, copyright 2014).
> Update README to bring it in line with styleguide

- app/controllers/anonymous_feedback/document_types_controller.rb
- app/controllers/anonymous_feedback/export_requests_controller.rb
- app/controllers/anonymous_feedback_controller.rb
- app/models/anonymous_contact.rb
- app/models/content_item.rb
- app/models/feedback_export_request.rb
- app/workers/content_item_populate_doctype_worker.rb
- config/routes.rb
- db/migrate/20171204124407_add_document_type_to_content_items.rb
- db/migrate/20171204155340_populate_document_type_for_content_items.rb
- db/structure.sql
- lib/content_store_lookup.rb
- lib/fix_misreported_done_page_service_feedback.rb
- lib/looked_up_content_item.rb
- spec/controllers/anonymous_feedback/document_types_controller_spec.rb
- spec/controllers/anonymous_feedback/export_requests_controller_spec.rb
- spec/controllers/anonymous_feedback_controller_spec.rb
- spec/factories/anonymous_feedback.rb
- spec/lib/content_item_lookup_spec.rb
- spec/models/anonymous_contact_spec.rb
- spec/models/feedback_export_request_spec.rb
- spec/requests/anonymous_feedback_feed_spec.rb
Add endpoints for searching for feedback by:
- multiple paths for feedback
- document type 
Also adds migration to populate the `document_type` for content items. 
For: https://trello.com/c/IB9P5EyE/266-introduce-new-browse-options-for-feedex
> Add search by format and by multiple paths

- app/models/anonymous_contact.rb
PostgreSQL isn’t able to use the path index when matching against an
array of patterns. Switching this to generate `OR`ed conditions speeds
this up by using the index again.
Before: https://explain.depesz.com/s/lIIG
After: https://explain.depesz.com/s/tZJ9
This wasn’t too bad for actual queries for data because the `created_at`
index was used as a pre filter. However on `COUNT` queries to determine
total number of responses, a full table scan was needed.
> Use ORs for multiple path matching instead of LIKE ANY

- Gemfile
- Gemfile.lock
- app/controllers/feedback_by_day_controller.rb
- app/models/feedback_by_day.rb
- config/routes.rb
- spec/models/feedback_by_day_spec.rb
- spec/rails_helper.rb
- spec/requests/feedback_by_day_spec.rb
content-performance-manager needs to retrieve metrics on the number of comment for each content item by day in order to populate it's data warehouse.
This PR implements a new endpoint /feedback-by-day that exposes this information.
the Trello card is [Expose Feedex numbers via Support API](https://trello.com/c/6nz6zXEE/113-5-expose-feedex-numbers-via-support-api)
> Add endpoint to retrieve the count of feedback by day

- config/initializers/new_framework_defaults.rb
`false` is the default value in Rails 5.0 / 5.1, and this option is no
longer supported in Rails 5.2.  Rails 5.2 has the same behaviour as
setting this to `false` in Rails 5.0 / 5.1.
For more, see https://blog.bigbinary.com/2016/02/13/rails-5-does-not-halt-callback-chain-when-false-is-returned.html
> Remove no-op configuration option

- db/migrate/20180906145408_add_index_to_content_items_organisations_organisation_id.rb
- db/structure.sql
This makes a query which is currently taking around 20 seconds to run, complete in 320ms.
Found by looking in the Postgres logs for slow running queries.
[Trello Card](https://trello.com/c/VztlS695/447-investigate-options-for-reducing-load-on-the-production-postgres-primary)
> Add an index on organisation_id to content_item_organisations

- app/models/content_item.rb
- config/brakeman.ignore
- spec/factories/anonymous_feedback.rb
This PR includes a few small changes to the `summary` and `doctype_summary` methods on `ContentItem`s to introduce some performance enhancements.
[Trello Card](https://trello.com/c/VztlS695/447-investigate-options-for-reducing-load-on-the-production-postgres-primary)
> Speed up ContentItem summary queries

- app/models/feedback_export_request.rb
This means that people who receive the emails and don't have access to the `govuk.digital` domain can still view the links.
[Trello Card](https://trello.com/c/25iiQBNZ/572-fix-urls-used-in-emails-sent-by-backend-apps-specifically-support-support-api-probably-others)
> Make sure URLs to support in emails are external

- Gemfile
- Gemfile.lock
- app/controllers/anonymous_feedback/content_improvement_controller.rb
- app/models/content_improvement_feedback.rb
- app/workers/content_improvement_feedback_worker.rb
- config/routes.rb
- db/migrate/20190130105818_create_content_improvement_feedback.rb
- db/structure.sql
- spec/factories/content_improvement_feedback.rb
- spec/models/content_improvement_feedback_spec.rb
- spec/requests/content_improvement_feedback_spec.rb
Trello: https://trello.com/c/a9WXTd6f/64-build-a-feedback-component-to-sit-below-business-finder-results
Add and endpoint to capture feedback from the EU Exit business finder.
We want to build a feedback component that sits at the bottom of the business finder results that allows users to tell us what's missing. 
There is a [related PR in feedback](https://github.com/alphagov/feedback/pull/630) that sends the feedback to support API
> Add endpoint to capture business finder feedback

- config/routes.rb
- spec/controllers/anonymous_feedback_controller_spec.rb
Currently the only way to perform a query against anonymous feedback using support-api is via a GET. This limits the number of paths that can be passed in to the limit of a URL length. In practice, this means you can only query on at most 30 URLs. The analytics team would like to be able to run queries with more than 30 URLs.
This is the first part of a bigger to change which will also see the support app use POST to run these queries.
[Trello Card](https://trello.com/c/EGvu5WoK/757-make-feedex-able-to-return-results-for-larger-sets-of-urls-by-changing-request-from-get-to-post)
> Allow querying for anonymous feedback using POST

- app/controllers/anonymous_feedback_controller.rb
- config/routes.rb
This follows on from https://github.com/alphagov/support-api/pull/305. Unfortunately that method only appeared to work because the tests were passing, but it doesn't actually set up the correct routes because of the `only: :index`. There doesn't appear to be a way to allow the `create` method of a resource to point to the same action as the `index` action, so instead I've made the routes explicit.
An alternative would have been to put this in the controller, but I decided it was better to keep the controller clean:
```ruby
def create; index; end
```
[Trello Card](https://trello.com/c/EGvu5WoK/757-make-feedex-able-to-return-results-for-larger-sets-of-urls-by-changing-request-from-get-to-post)
> Correctly allow POST requests to anonymous feedback endpoint

- app/workers/problem_report_daily_totals_pp_uploader_worker.rb
- spec/models/workers/problem_report_totals_pp_upload_spec.rb
support-api doesn't have a bearer token set for support-api, so the
gds-api-adapters call was failing.  Rather than add a bearer token so
that support-api can talk to itself, just make the worker call the
appropriate thing directly.
> Do not use gds-api-adapters to talk to self in daily PP worker

- config/application.rb
This application doesn't use Sprockets, so don't require the gem.
> Don't require sprockets

- lib/organisation_importer.rb
It used to be in Whitehall Admin, but has now moved to
Collections. Switch to using the helper method from the GdsApi module,
so that the default from the gds-api-adapters is used.
> Fix talking to the Organisations API

- app/mailers/global_export_notification.rb
- app/views/global_export_notification/notification_email.text.erb
- app/workers/generate_feedback_csv_worker.rb
- app/workers/generate_global_export_csv_worker.rb
- lib/s3_file_uploader.rb
- spec/mailers/global_export_notification_spec.rb
- spec/workers/generate_global_export_csv_worker_spec.rb
Use S3 to transfer files, to be consistent with other emails and also compatible (in future) with Notify.
https://trello.com/c/V9wtOj6x/1713-3-support-api-make-globalcsvexport-use-s3-instead-of-email-attachments
> Upload exported CSV file to S3 rather than attaching it

- app/mailers/global_export_notification.rb
- app/views/global_export_notification/notification_email.text.erb
- app/workers/generate_feedback_csv_worker.rb
- app/workers/generate_global_export_csv_worker.rb
- lib/s3_file_uploader.rb
- spec/mailers/global_export_notification_spec.rb
- spec/workers/generate_global_export_csv_worker_spec.rb
Use S3 to transfer files, to be consistent with other emails and also compatible (in future) with Notify.
This is reapplying #411 and fixing a bug it introduced. (Reverted in #413.)
The actual fix compared with #411 is quite small: use `public_url` not `key`, and ensure that `public: true` is set when creating the file. I've also added tests to ensure that this is correct — the problem previously was that although uploading was tested, and sending the email was also tested, the email was sent with a dummy URL and the step of generating an email using the data from the upload step (i.e., the call to `.notification_email().deliver_now` was never tested).
https://trello.com/c/V9wtOj6x/1713-3-support-api-make-globalcsvexport-use-s3-instead-of-email-attachments
> Switch global export to s3

- app/workers/generate_global_export_csv_worker.rb
- lib/s3_file_uploader.rb
- spec/workers/generate_global_export_csv_worker_spec.rb
Files can't be publicly accessible in the s3 bucket. Existing uploads are proxied through the support app which handles authentication and retrieves the file if permitted; this changes global export requests to use the same process.
https://trello.com/c/V9wtOj6x/1713-3-support-api-make-globalcsvexport-use-s3-instead-of-email-attachments
> Make global export requests proxy files through support app

- Gemfile
- Gemfile.lock
- config/application.rb
- config/environments/development.rb
- config/environments/production.rb
- config/initializers/mailer.rb
- config/secrets.yml
- lib/notify_delivery_method.rb
- spec/lib/notify_delivery_method_spec.rb
We want to switch to using GOV.UK Notify instead of Amazon SES for emails. This instantiates the Notify client and configures ActionMailer to use it.
https://trello.com/c/GZ142gQv/1730-5-support-api-use-notify-instead-of-amazon-ses-%F0%9F%8D%90
> Use GOV.UK Notify for ActionMailer messages

- config/initializers/mailer.rb
Notify needs an API key and template ID; pass these through from the environment (puppet/secrets) when instantiating a mailer.
> Pass through Notify configuration parameters

- spec/models/content_item_spec.rb
- spec/requests/organisations_spec.rb
In https://github.com/alphagov/support-api/pull/462 rubocop "fixed" the
indentation and in these few cases it didn't do a great job.
This applies a more consistent indentation which is both accepted by
rubocop and more widely used.
> Amend indentation autocorrect by rubocop

- Gemfile
- Gemfile.lock
- spec/rails_helper.rb
- spec/spec_helper.rb
https://trello.com/c/epNWudCR/176-write-an-rfc-for-continuous-deployment-and-seek-review
Note that the RCov formatter is optional, and we can still see a
webpage of the detailed coverage.
> Always print coverage after running tests

- config/schedule.rb
We're seeing a number of errors in Sentry as a result of at least
two workers (but probably more): `ProblemReportStatsPPUploaderWorker`
and `ProblemReportDailyTotalsPPUploaderWorker`.
These result in `GdsApi::SocketErrorException` timeouts on
Integration, most likely as a result of the nightly data sync,
where the dependent services (e.g. Performance Platform) are
temporarily down.
We shouldn't care about running these scheduled tasks on
Integration and Staging, particularly as they're all timed during
the data sync. It is better instead to let the tasks happen on
Production and wait for the nightly data sync to copy the results
over to Staging and Integration.
This does mean that Production may be 24 hours 'ahead' of the
other environments, but given that Performance Platform is being …
> Don't schedule Rake tasks outside of the Production environment

- Jenkinsfile
Uses Postgres13 for CI by setting the TEST_DATABASE_URL environment variable.
- Confirmed CI on [this](https://ci.integration.publishing.service.gov.uk/job/support-api/job/postgres_13_test/1/console) branch (`Dropped database 'support-api-test'`) was building a different database than on the [main](https://ci.integration.publishing.service.gov.uk/job/support-api/job/main/518/console) branch (`Dropped database 'support_api_test'`)
- Confirmed tests pass
Trello:
https://trello.com/c/lYPj0Poj/7-support-api
https://trello.com/c/B21t1VAD/956-upgrade-support-api-from-postgres-96-to-postgres-13
> Use Postgres13 for CI

- spec/lib/distributed_lock_spec.rb
- spec/presenters/problem_report_presenter_spec.rb
- spec/workers/content_item_enrichment_worker_spec.rb
- spec/workers/content_item_populate_doctype_worker_spec.rb
This PR increases code coverage from 90.86% to 96.56%, in preparation for enabling Continuous Deployment, which has an advisory code coverage minimum of 95% ([1]).
Trello: https://trello.com/c/855eZgel/2850-enable-continuous-deployment-for-support-api-3
[1]: https://github.com/alphagov/govuk-rfcs/blob/main/rfc-128-continuous-deployment.md#check-internal-repo-tests-pass-ie-features-are-tested-in-detail
> Increase code coverage in advance of enabling CD

- config/environments/production.rb
This was removed as part of the Rails 7 upgrade. It was discussed
a little here:
https://github.com/alphagov/support-api/pull/628#discussion_r832024631
In retrospect, this has caused emails to fail to be sent. Related
Zendesk tickets:
- https://govuk.zendesk.com/agent/tickets/4932239
- https://govuk.zendesk.com/agent/tickets/4931891
- https://govuk.zendesk.com/agent/tickets/4927683
> Specify Notify delivery method

- .dockerignore
- Dockerfile
- config/initializers/gds_api.rb
- config/puma.rb
- config/sidekiq.yml
Add Dockerfile which is standard we use for Ruby Apps
Add .dockerignore to keeps image clean
Adds Puma via govuk_app_config
https://trello.com/c/44ebF691/1026-publishing-journey-apps-migrations
> Dockerised app to meet replatforming standards.

- app/zendesk_tickets/problem_report.erb
- lib/zendesk/problem_report_ticket.rb
This just gets rid of the deprecation warnings in the logs. No functional change.
> Switch from deprecated `Plek.current` to `Plek.new`.

- lib/organisation_importer.rb
Unclear why this class was using it's own longer - but doesn't seem to do anything special expect use JSON formatting and only output in production. This caused an issue with running the `api_sync:import_organisations` rake task on Kubernetes as the logger was configured to write to a file instead of stdout. (Containers have readonly file permissions).
> Use the default Rails logger for organisation importer

- config/brakeman.ignore
- lib/distributed_lock.rb
Removes the original lock, moving us to the simplified lock name added here: https://github.com/alphagov/support-api/pull/778
Can be merged once a safe period of time has passed (min 24 hours after original pull merged, so Thu May 18th would be reasonable)
https://trello.com/c/84yWQ0NJ/1662-ps-15-clean-up-brakeman-errors-following-on-from-rediscurrent-redisnew-updates
> Remove original lock now a safe time has passed

- lib/duplicate_detector.rb
- spec/models/duplicate_detector_spec.rb
User's of the Feedback Explorer service are finding it time
consuming to manually remove duplicate entries in the CSV export
they generate for 23 services each month (e.g. /done/view-driving-licence).
The rake task `anonymous_feedback_deduplication:recent` is scheduled
to run every 5 minutes to process any duplicates found. It's currently
removing records being created multiple times within a 5 second period.
This is a known long term issue and was originally introduced in
https://github.com/alphagov/support/pull/144
Most of the duplicate records reported are generated within 5 minutes
of each other. From inspecting the data we suspect it's from people
clicking the submit button twice, or hit the back button after submitting.
Increasing the interval range should significantly reduce the …
> Increase feedback duplicate detector interval range 

- app/controllers/support_tickets_controller.rb
- app/models/support_ticket.rb
- config/routes.rb
- spec/models/support_ticket_spec.rb
- spec/requests/support_tickets_spec.rb
We want to make it easy for any app to create a support ticket and support-api feels like the best place for this.
The endpoint `/support-tickets` will be made available to apps via [gds-api-adapters](https://github.com/alphagov/gds-api-adapters), which allows them to pass Zendesk ticket parameters to support-api.
The [gds_zendesk](https://github.com/alphagov/gds_zendesk) gem provides a client to communicate with Zendesk and it has a `ticket.create!` method, which is called if the parameters provided are valid.
The only required standard ticket fields are `subject` and `description` - for more information see https://support.zendesk.com/hc/en-us/articles/4408886739098-About-ticket-fields
This provides the basis of creating Zendesk tickets and will need adjustments once we know what other …
> Allow any app to create support tickets

- .gitignore
- Gemfile
- Gemfile.lock
- Rakefile
- spec/service_consumers/pact_helper.rb
This adds Pact contract testing as per the [Pact testing Developer docs](https://docs.publishing.service.gov.uk/manual/pact-testing.html) and has been tested locally with the consumer branch of gds-api-adapters ([add-support-api-pact-tests](https://github.com/alphagov/gds-api-adapters/tree/add-support-api-pact-tests)).
Consumer PR: https://github.com/alphagov/gds-api-adapters/pull/1273
Trello card: https://trello.com/c/QBYirV6S/3494-add-pact-test-for-create-support-tickets-endpoint-5
> Configure Pact tests provider

- .github/workflows/ci.yml
- .github/workflows/pact-verify.yml
- spec/service_consumers/pact_helper.rb
This workflow will verify via the deployment pipeline that each new build of support-api honours it's contract tests with gds-api-adapters.
Related PRS:
- https://github.com/alphagov/gds-api-adapters/pull/1273
- https://github.com/alphagov/support-api/pull/964
Trello card: https://trello.com/c/QBYirV6S/3494-add-pact-test-for-create-support-tickets-endpoint-5
> Add GitHub Action workflow for verifying pact tests

- .github/workflows/pact-verify.yml
Closing brackets was missing resulting in `Don't know how to build task 'pact:verify:at[tmp/pacts/gds_api_adapters-support_api.json'` error in gds-api-adapters.
See failing CI:
- https://github.com/alphagov/gds-api-adapters/actions/runs/9566384476/job/26371607850?pr=1274
- https://github.com/alphagov/gds-api-adapters/actions/runs/9566383671/job/26371597965?pr=1274
[Trello](https://trello.com/c/QBYirV6S/3494-add-pact-test-for-create-support-tickets-endpoint-5)
---
> Fix Pact verify workflow

- app/models/support_ticket.rb
- spec/models/support_ticket_spec.rb
- spec/requests/support_tickets_spec.rb
- Use the comment property to set the Zendesk ticket description
- Don't format ticket body in SupportTicket as those will be coming in formatted
- Remove `user_agent`, if necessary it will be in the body
See commit messages for details. Tested in integration. This endpoint is not currently used.
Zendesk API reference: https://developer.zendesk.com/api-reference/ticketing/tickets/tickets/
---
> Update support tickets endpoint part1

- Gemfile
- Gemfile.lock
- config/initializers/gds_zendesk.rb
- lib/zendesk/dummy_client.rb
- spec/helpers/zendesk_test_helpers.rb
- spec/lib/zendesk_dummy_client_spec.rb
- spec/support/gds_zendesk_helpers.rb
"gds_zendesk" will be retired.
Tested in integration:
```
attr = {:subject=>"Testing support api",
"tags"=>["govt_form", "technical_fault", "fault_with_content_data", "govuk_platform_support", "slack_has_been_notified"],
"comment"=>{"body"=>"Testing. Assign to Aga Dufrat (2nd line — GOV.UK Alerts and Issues)"}}
GDS_ZENDESK_CLIENT.ticket.create!(attr)
```
The following Zendesk ticket was created: https://govuk.zendesk.com/agent/tickets/5893971
---
> Use "zendesk_api" gem instead of "gds_zendesk"

- app/controllers/support_tickets_controller.rb
- app/models/support_ticket.rb
- spec/models/support_ticket_spec.rb
- spec/requests/support_tickets_spec.rb
Add additional Zendesk ticket attributes:
- priority
- requester
- collaborators
- custom_fields
- ticket_form_id
Those are required by apps that create Zendesk tickets:
- https://github.com/alphagov/support/blob/main/app/models/zendesk/zendesk_tickets.rb
- https://github.com/alphagov/smart-answers/blob/main/lib/support_ticket.rb
- https://github.com/alphagov/feedback/blob/main/app/lib/support_ticket_creator.rb
Tested in integration with the most complex [ticket](https://govuk.zendesk.com/agent/tickets/5894126).
https://github.com/alphagov/support/issues/1422
---
Follow [these …
> Update create support ticket endpoint

- app/models/support_ticket.rb
- spec/helpers/zendesk_test_helpers.rb
- spec/models/support_ticket_spec.rb
- spec/requests/support_tickets_spec.rb
It's not possible to create Zendesk ticket if a requester is suspended in Zendesk. The following error is raised:
```
ZendeskAPI::Error::RecordInvalid:
{"requester"=>[{"description"=>"Requester: <Name> is suspended."}]}
(ZendeskAPI::Error::RecordInvalid)
```
We don't want to rescue ZendeskAPI::Error::RecordInvalid as this error is raised for other issue such as incorrect formatting.
Suspended users can be found https://govuk.zendesk.com/agent/user_filters
Tested in integration using Support app
```
attr = {
:subject=>"Testing support api",
"tags"=>["govt_form", "technical_fault", "fault_with_content_data", "govuk_platform_support", "slack_has_been_notified"],
"descreption"=>Testing. Assign to Aga Dufrat (2nd line — GOV.UK Alerts and Issues)"},
requester: { "email" => "<PPI-REDACTED>", …
```
> Check if requester is suspended before creating Zendesk ticket

- app/controllers/support_tickets_controller.rb
- spec/helpers/zendesk_test_helpers.rb
- spec/requests/support_tickets_spec.rb
Otherwise 500 error is returned. The Client apps can then handle those appropriately.
Ideally calling Zendesk API should be done in a worker that would handle all possible Zendesk API errors with appropriate retry logic (e.g. don’t retry on 409 :conflict). The controller should respond with 202 :accepted status rather than 201 :created.
It is not implemented at this time due to change in delivery priorities (and this work being reprioritised).
https://github.com/alphagov/support/issues/1422
--- 
> Handle ZendeskAPI::Error::RecordInvalid errors

- Gemfile
This was added in f9a5adfc68b173dcbf229e342470bd0930583ec0, presumably so it could be used in 38721ae0d277d4a0f7160213cf9ded6decb04037. However this was removed in dce718f019bbde308dfcafe2de3d9da9d48e8a95.
None of the remaining gems reference a git repo, so there is no need to include the git source in the Gemfile.
> Remove git source from Gemfile

- app/sidekiq/generate_feedback_csv_job.rb
- app/sidekiq/generate_global_export_csv_job.rb
- spec/models/sidekiq/generate_feedback_csv_job_spec.rb
- spec/sidekiq/generate_global_export_csv_job_spec.rb
We have set up our Notify accounts to not send emails in integration and staging, unless the email address is a considered a “team member”.  This is deliberate to stop users from receiving duplicated emails from production plus integration/staging.
Notify returns an error if you try to send an email address is someone who isn’t a team member:
```
Notifications::Client::BadRequestError
BadRequestError: Can't send to this recipient using a team-only API key
```
In most apps (e.g. in Whitehall and Publisher) we don’t log these to Sentry, as they serve no purpose and are not actionable.
Making the same change here, so these are no longer logged to Sentry in those environments.
[Trello card](https://trello.com/c/uber1mpV)
> Do not report team only requests to Sentry in integration and staging

- app/models/problem_report.rb
- spec/models/problem_report_spec.rb
We are seeing bots submitting our problem report form with content that contains null bytes. This results in an exception being raise: `ArgumentError string contains null byte (ArgumentError)`.
These characters serve no purpose, so we should reject them. This will remove the Sentry alerts and stop spam that contains these characters.
> [PP-7236] Reject null bytes in problem reports
